
language: objective-c
matrix:
  include:
    - osx_image: xcode9
      objective-c: "stable"

script:
  xcodebuild test -project Samples/BlocklySample/BlocklySample.xcodeproj  -scheme BlocklyTests
                  -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0'
                  -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
                  -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4'
                  -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch),OS=9.3'
