
language: objective-c
matrix:
  include:
    - osx_image: xcode8.3
      objective-c: "stable"

script:
  xcodebuild test -project Samples/BlocklySample/BlocklySample.xcodeproj  -scheme BlocklyTests
                  -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3'
                  -destination 'platform=iOS Simulator,name=iPad 2,OS=8.3'
                  -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch),OS=9.3'
